name: Reusable Build & Test

on:
  workflow_call:
    inputs:
      configuration:
        type: string
        required: false
        default: 'Release'
        description: 'Build configuration'
      dotnet-version:
        type: string
        required: false
        default: '10.0.x'
        description: 'Dotnet SDK version'

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build, Test and Prepare Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Run repository MSBuild (build & test)
        run: |
          echo "Invoking MSBuild build-and-test targets"
          dotnet msbuild Build.proj /t:Restore;BuildPackages;BuildTests;Test /p:Configuration=${{ inputs.configuration }} /v:minimal

      - name: Normalize text file encodings to UTF-8
        if: always()
        run: pwsh -NoProfile -NonInteractive -File ./scripts/convert-files-to-utf8.ps1

      - name: Collect XML docs
        run: |
          mkdir -p artifacts/docs
          # copy generated XML doc files from projects
          find . -type f -path "*/bin/Release/net10.0/*.xml" -print0 | xargs -0 -I{} cp {} artifacts/docs/ || true
          # include docs/ markdown content
          find . -type d -name docs -prune -print0 | while IFS= read -r -d '' d; do cp -r "$d" artifacts/docs/ || true; done

      - name: Upload build/test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            artifacts/docs
            artifacts/test-results/**/*.trx
          retention-days: 7
