name: CI Build & Test

on:
  push:
    branches: [ main, develop, 'feature/**', 'fix/**', 'release/**' ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '10.0.x'
  DOTNET_CLI_TELEMETRY_OPTOUT: true

permissions:
  contents: read

jobs:
  call-build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      configuration: 'Release'

  generate-deps:
    name: Generate package-dependencies.json
    runs-on: ubuntu-latest
    needs: call-build-and-test
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure PowerShell is available
        run: |
          pwsh -c "Write-Host 'PowerShell available:' $PSVersionTable.PSVersion"

      - name: Run generator
        run: pwsh -NoProfile -NonInteractive -File ./scripts/generate-package-dependencies.ps1

      - name: Upload package-dependencies.json
        uses: actions/upload-artifact@v4
        with:
          name: package-deps
          path: package-dependencies.json
          retention-days: 7

  upload-artifacts:
    name: Upload additional artifacts
    runs-on: ubuntu-latest
    needs: [call-build-and-test, generate-deps]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ci-artifacts
          path: artifacts

      - name: Download package-deps artifact
        uses: actions/download-artifact@v4
        with:
          name: package-deps
          path: .

      - name: Upload combined artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-combined
          path: |
            artifacts/docs
            package-dependencies.json
            artifacts/test-results/**/*.trx
          retention-days: 7
