name: CI Build & Test

on:
  push:
    branches: [ main, develop, 'feature/**', 'fix/**', 'release/**' ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '10.0.x'
  DOTNET_CLI_TELEMETRY_OPTOUT: true

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build, Test and Prepare Artifacts
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Run repository MSBuild CI target
      run: |
        echo "Invoking MSBuild CI target"
        dotnet msbuild Build.proj /t:CI /p:Configuration=Release /v:minimal

    - name: Collect XML docs
      run: |
        mkdir -p artifacts/docs
        # copy generated XML doc files from projects
        find . -type f -path "*/bin/Release/net10.0/*.xml" -print0 | xargs -0 -I{} cp {} artifacts/docs/ || true
        # include docs/ markdown content
        find . -type d -name docs -prune -print0 | while IFS= read -r -d '' d; do cp -r "$d" artifacts/docs/ || true; done

    - name: Generate package-dependencies.json (PRs and manual)
      if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      run: pwsh -NoProfile -NonInteractive -File ./scripts/generate-package-dependencies.ps1

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ci-artifacts
        path: |
          artifacts/docs
          package-dependencies.json
          artifacts/test-results/**/*.trx
        retention-days: 7
